### PR TITLE
Added -HHMM (local time) to branch names to avoid conflicts for manual runs.

### PR DESCRIPTION
**Pull request by jbum**

### CODE REVIEW

**Comment by carterm** [comment]
Er, don't we want subsequent runs to update the PR?

**Comment by jbum** [comment]
There's normally only one run per day. Thus far, when when the cron fails whatever reason, we do a manual run to a new PR (e.g. I kept adding jbum1, jbum2, etc.) the other day, and close out the old one.

**Comment by carterm** [comment]
I feel like we don't need this anymore since this PR makes it work on existing PRs.
https://github.com/cagov/Cron/pull/48

**Comment by jbum** [comment]
No longer needed.

**Pull request closed without merging**
