### PR TITLE
CCG-1221. Added missing crawls.

### PR DESCRIPTION
**Pull request by jbum**
We noticed several recently added pages (including /equity/ and /travel/) were missing from the QnA crawl script.

@aaronhans I added all the missing pages from the sitemap.  This increases QnAs from 268 -> 302.  However, I'm noticing some dupes, perhaps because one or more of these pages are aliases.

These are the dupes:

found dup Drive-through testing in Northern California
found dup Drive-through testing in Southern California
found dup Is there an over-the-counter COVID-19 test I can take at home?
found dup Is there a prescription COVID-19 test I can take at home?
found dup How long does it take for coronavirus test results to come back?
found dup Who should get tested for coronavirus?
found dup When can I be around other people after I tested positive for COVID-19 but had no symptoms?
found dup If I test positive for COVID-19 in a viral test, what should I do to protect others in my household?
found dup How do I get a drive-through test with Verily?
found dup Why am I asked to create an account for testing with Verily?
found dup How can I find a coronavirus testing location near me?

The dupes seem harmless, but let me know if you there's a URL or three we should remove from the crawl.

### CODE REVIEW

**Comment by aaronhans** [comment]
Thanks for noticing dups. We often have real duplicates on site content because the content team thinks the info should be in both places.

We don't want to put dups into the quick answers dataset because it will return dups to the user

**Comment by aaronhans** [comment]
The content team can flag an accordion so that it is not included in the crawler by adding the class js-qa-exclude, info in the readme https://github.com/cagov/Cron/tree/master/qnacrawler

**Comment by jbum** [comment]
I believe the code is already doing the correct thing for the dupes - these are just warnings I wasn't seeing before...

**Comment by jbum** [comment]
Dupes are fixed :)

**Review by aaronhans — APPROVED** [review]
cool

**Pull request merged**
