### PR TITLE
Auto approving translations

### PR DESCRIPTION
**Pull request by carterm**
Poll the PR list every 5 minutes and look for open translation labeled PRs that have passed all their checks.  Merge them and delete branches.  Works on the oldest first.  Stops processing if the oldest PR does not pass.  Not pass could mean "in progress" or "completed and failed".

### CODE REVIEW

**Review by chachasikes — COMMENTED** [review]
Read the code.

I like that the Slackbot will report an error.

**Review by aaronhans — COMMENTED** [review]
This is good code and a great service I like how we already have build checks in place so we are sure these updates aren't going to break the pipeline

I don't think we should auto approve PRs from our external partner without more stringent verification steps though. We could make sure that the only files modified are in the translated_posts directory and that they don't contain any script tags that weren't in the original post or something

I think this exact code and process could be extremely useful if we used it for merging dependabot package updates. Especially if we also added an execution of an end to end test suite before approval.

**Comment by carterm** [comment]
Ensuring that the only files modified are in the "translated-posts" folder.

**Comment by carterm** [comment]
Ensuring that files are "modified" only.  No new files here.  Will need to update the Wordpress process so that it creates placeholders for new content (should have done that anyway).

**Review by aaronhans — APPROVED** [review]
nice updates

**Pull request merged**
