### PR TITLE
package lock file version changes only

### PR DESCRIPTION
**Pull request by aaronhans**
These lockfileVersion changes are quite long, big new packages section on top of the familiar dependencies section, more info on the big lockfileVersion update here https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson.html and https://blog.npmjs.org/post/618653678433435649/npm-v7-series-arborist-deep-dive

These changes are generated by running the following commands on a clean branch off master on a machine running npm v7

rm -r node_modules
npm install

The previous package-lock file was present when npm install ran

### CODE REVIEW

**Comment by aaronhans** [comment]
I recommend merging this in the morning after initial data updates

**Comment by chachasikes** [comment]
ok - we have blueprint update as well tomorrow @aaronhans which is done by noon

**Review by jbum — APPROVED** [review]

**Comment by carterm** [comment]
Everytime I do npm install it changes the version back to 1. ?

**Review by carterm — APPROVED** [review]
Uncaught Error: Cannot find module 'universalify'

**Comment by carterm** [comment]
> Tested. Works for me.

**Review by carterm — CHANGES_REQUESTED** [review]
getting ..Uncaught Error: Cannot find module 'universalify'

**Comment by aaronhans** [comment]
> getting ..Uncaught Error: Cannot find module 'universalify'

Are you running one of these services in debug mode to test it? I am running newsfeed and translation approvals successfully in debug mode in this branch

**Comment by carterm** [comment]
> > getting ..Uncaught Error: Cannot find module 'universalify'
> 
> Are you running one of these services in debug mode to test it? I am running newsfeed and translation approvals successfully in debug mode in this branch

After I manually install 'universalify' it works.

**Review by carterm — APPROVED** [review]
A fresh node-modules install and it works.

**Pull request merged**
