### PR TITLE
Equity data single commit - fast

### PR DESCRIPTION
**Pull request by carterm**
Making the equity data update in a single commit.

Some unrelated improvements extracted to a pre-PR here...
https://github.com/cagov/Cron/pull/66

### CODE REVIEW

**Review by jbum — APPROVED** [review]
Looking forward to seeing this in action!  Thanks for making this a V2 since it's a pretty big change.

**Comment by carterm** [comment]
Now this PR is easier to review

**Review by chachasikes — APPROVED** [review]
Very exciting improvement!

**Comment by abquirarte** [comment]
Nice work team! 🤓

**Review by aaronhans — APPROVED** [review]
amazing stuff!

**Pull request merged**
