### PR TITLE
(draft) Crondo (cron scheduler)

### PR DESCRIPTION
**Pull request by carterm**
Can schedule cron functions to run on daily schedules in one place.

(Rewriting based on new requirements)

(Draft, work in progress)

### CODE REVIEW

**Review by jbum — APPROVED** [review]
This is gonna be great :)

**Review by aaronhans — APPROVED** [review]
Pretty cool Carter! 
I have many questions:
Do other function triggers need to be retired before this is merged?
This is running every 5 minutes now right? I wonder if we are entering a use case that makes the FAAS less efficient than a constantly available server.

Would be great if you could run the whole engineering team through this next week.

**Comment by carterm** [comment]
Thinking I will make a separate product for this.

**Comment by jbum** [comment]
Hey @carterm this is almost a year old. Is it a lost cause? Should we close the PR?

**Comment by carterm** [comment]
Closing the PR.  Other plans will make this obsolete.

**Pull request closed without merging**
