### PR TITLE
Using baked in age group value (Wait for CDPH review)

### PR DESCRIPTION
**Pull request by carterm**
For making the age unknown values consistent with the data.
https://digital-ca-gov.atlassian.net/browse/CCG-1982

Age -3 will be considered 0-17.

"Unknown Agegroup" will be converted to "Unknown" to match our JSON schema.

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
Excellent! Thanks Carter

Let's not merge until we get approval from CDPH

**Comment by aaronhans** [comment]
@carterm this file has moved, could we make this change on the file in the new location and generate a chart with the unknown bar displayed using latest SQL

**Comment by carterm** [comment]
Updated and tested

**Comment by carterm** [comment]
Obsolete if this is merged...
https://github.com/cagov/Cron/pull/199

**Pull request merged**
