### PR TITLE
D3 Dashboard Bottom Vaccines Demographics Data

### PR DESCRIPTION
**Pull request by carterm**
Allows D3 tables for v2-state-dash

Also included JSON validation for output.

Separated D3 dataset from daily stats.

Reorg for JSON schema and SQL files.

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
nice

**Review by chachasikes — APPROVED** [review]

**Review by chachasikes — APPROVED** [review]
Amazing!

**Review by aaronhans — APPROVED** [review]
This is fantastic Carter!

Want to add a script section to the package.json to trigger this test? You can mess with that in a future PR. Great to see this working already!

**Review by jbum — APPROVED** [review]

**Review by aaronhans — APPROVED** [review]
nice refactor

**Review by jbum — APPROVED** [review]
It might be good to run these and have them generate PRs, so we can do eyeball the data before/after and make sure everything is copacetic.

**Review by chachasikes — APPROVED** [review]
I see the .sql paths change - I'll make a note to update our data docs

**Pull request merged**
